import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

import "./globals.css";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "TrueB00L",
  description: "Generated by create next app. Refuse AI <3",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`--font-mono h-full antialiased`}>
      <body
        className={`${jetBrainsMono.className} min-h-full flex flex-col crt-filter`}
      >
        <Header />
        <main className="flex flex-col pl-10 pr-10 m-5 gap-5">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
